jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_DOMAIN=${{ secrets.NEXT_PUBLIC_API_DOMAIN }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> $GITHUB_ENV
          echo "NEXTAUTH_URL_INTERNAL=${{ secrets.NEXTAUTH_URL_INTERNAL }}" >> $GITHUB_ENV
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> $GITHUB_ENV
          echo "CLOUDNARY_CLOUD_NAME=${{ secrets.CLOUDNARY_CLOUD_NAME }}" >> $GITHUB_ENV
          echo "CLOUDNARY_SECRET=${{ secrets.CLOUDNARY_SECRET }}" >> $GITHUB_ENV
          echo "CLOUDNARY_API_KEY=${{ secrets.CLOUDNARY_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GOOGLE_GEOCODING_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_GEOCODING_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_MAPBOX_API_KEY=${{ secrets.NEXT_PUBLIC_MAPBOX_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Start application using PM2
        run: pm2 restart example || pm2 start npm --name example -- run start
